### ISSUE TITLE
Cannot wrap null or non-object

### ISSUE THREAD

**Issue by Pampattitude** [falsecz/node-hbase#3]
Hi,

I'm having trouble using node-hbase with HBase 1.0.0. I get the following error:

```
app-0 (err): 2015-03-02 14:19:18 +00:00: 2015-03-02T14:19:18.803Z - error: app.js:22: UNC Error: Cannot wrap null or non-object
app-0 (err):     at Function.ByteBuffer.wrap (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/node_modules/bytebuffer/ByteBuffer.js:232:23)
app-0 (err):     at ProtoBuf.Reflect.Field.verifyValue (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:2466:39)
app-0 (err):     at Message.set (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:1741:69)
app-0 (err):     at Message (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:1671:38)
app-0 (err):     at ProtoBuf.Reflect.Field.verifyValue (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:2489:28)
app-0 (err):     at ProtoBuf.Reflect.Field.verifyValue (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:2416:39)
app-0 (err):     at Message.set (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:1741:69)
app-0 (err):     at Message (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:1671:38)
app-0 (err):     at ProtoBuf.Reflect.Field.verifyValue (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:2489:28)
app-0 (err):     at ProtoBuf.Reflect.Field.verifyValue (/home/safeuser/hbase-proxy-server/node_modules/node-hbase/node_modules/protobufjs/ProtoBuf.js:2416:39)
```

Using this as a put input (via `JSON.stringify(putListObjects)`):

```json
[{"row":"row1","familyMap":{"cf1":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"cf1":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"cf1":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":"row1","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":0,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":"","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":0,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":0,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":"Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Mobile/10B329","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":"N","timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"de":[{"qualifier":"a","value":1425305761,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}},{"row":""row1"","familyMap":{"da":[{"qualifier":"a","value":1425305761,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}}]
```

The put objects list is created as follows:
```javascript
    var putList = [];

    var dataKeys = Object.keys(data);
    for (var i = 0 ; dataKeys.length > i ; ++i) { // Column families                                                                                                                                        
        var cfKeys = Object.keys(data[dataKeys[i]]);
        for (var j = 0 ; cfKeys.length > j ; ++j) {
            var put = new hbase.Put(row);
            put.add(dataKeys[i], cfKeys[j], null === data[dataKeys[i]][cfKeys[j]] ? '' : data[dataKeys[i]][cfKeys[j]]);
            putList.push(put);
        }
    }

    return client.mput(table, putList, callback);
```

And the raw data given looks like this (excluding column family and row):

```json
app-0 (out): { de: 
app-0 (out):    { a: null,
app-0 (out):      b: null,
app-0 (out):      c: null,
app-0 (out):      d: '',
app-0 (out):      e: '',
app-0 (out):      f: '',
app-0 (out):      g: '',
app-0 (out):      h: '',
app-0 (out):      i: 0,
app-0 (out):      j: null,
app-0 (out):      k: 0,
app-0 (out):      l: 0,
app-0 (out):      m: 'Dalvik/1.6.0 (Linux; U; Android 4.1.2; LG-E431g Build/JZO54K)',
app-0 (out):      n: 'N',
app-0 (out):      o: 1425305958 },
app-0 (out):   da: { 'o#1425305958': 1425305958 } }
```

Note that, in the code snippet before, I replace all `null` with an empty string.
I do not understand what is wrong with this code. No `null` value is left inside the put objects, so I don't understand why a null value can happen.

Is this problem known or referenced?

--

Thanks a bunch!

Regards,

[EDIT]: fixed a bit of formatting. Sorry, english is not my native language!

**Comment by wision** [comment]
Hello,

you cannot store numbers like you are trying to.
{"row":"row1","familyMap":{"de":[{"qualifier":"a","value":0,"timestamp":{"low":-1,"high":2147483647,"unsigned":false}}]}}

the value (0 in this case) has to be either a string or a buffer.

**Comment by Pampattitude** [comment]
Thanks a bunch!

Shouldn't it be interesting to add this to the documentation, just to make sure there's no confusion about it in the future?

Thanks again!

**Comment by wision** [comment]
Yeap.. working on it!
You're welcome.
